### ISSUE TITLE
Block is no longer Sync in ratatui-widgets 0.3.1 (was Sync in 0.3.0)

### ISSUE THREAD

**Issue by ricott1** [ratatui/ratatui#2592]
### Description

`ratatui::widgets::Block` implemented `Sync` in `ratatui-widgets` 0.3.0 but does not in 0.3.1. This breaks code that stores a `Block` (or any widget containing one) in a `static`.

I think the cause is the new `shadow` field on `Block`, which holds `Arc<dyn CellEffect>` with no `Send + Sync` bound. `ratatui-widgets` 0.3.0 has no `shadow` field on `Block`, so `Block` was `Sync` there.

### To Reproduce

```rust
fn assert_sync<T: Sync>() {}

fn main() {
      assert_sync::<ratatui::widgets::Block<'static>>();
}
```

- Compiles with `ratatui-widgets = "0.3.0"`.
- Fails with `ratatui-widgets = "0.3.1"`:

```
error[E0277]: `(dyn CellEffect + 'static)` cannot be shared between threads safely
     = help: the trait `Sync` is not implemented for `(dyn CellEffect + 'static)`
     = note: required for `Arc<(dyn CellEffect + 'static)>` to implement `Sync`
  note: required because it appears within the type `ratatui_widgets::block::shadow::Effect`
  note: required because it appears within the type `Shadow`
  note: required because it appears within the type `Block<'static>`
```

### Expected

`Block` should remain `Sync`, as it was in 0.3.0.

**Comment by orhun** [comment]
fixed in #2584
